### ISSUE TITLE
Create action to receive user choice

### ISSUE THREAD

**Issue by skiadas** [skiadas/haskellMinesweeper#12]
- Write an `IO Action` value that receives input from the user and converts it into an `Action` value (see #11 you will need that issue done first). 
- You may find it helpful to have a function `String -> What` which converts some string expression of your choice to an appropriate "What" behavior. You probably don't want the user to literally have to type `Flag` for example, you may develop some shortcuts.

**Comment by DSkirvinC** [comment]
Managed to add both an IO action by the name of makeAction and a helper fucntion by the name of stringAct. stringAct converts key strings to their respective 'Act' and throw an error otherwise. makeAction takes user input and returns an 'Action' comprised of said input. Tests have been added for stringAct.
